apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o charts/fluxcapacitor -f fluxcapacitor-app/docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o charts/fluxcapacitor -f fluxcapacitor-app/docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/fluxcapacitor-app-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: GRAPHQL_LISTEN_PORT
              value: "4001"
            - name: GRAPHQL_URI
              value: http://api:4001/graphql
            - name: NEO4J_PASSWORD
              value: letmein
            - name: NEO4J_URI
              value: bolt://neo4j:7687
            - name: NEO4J_USER
              value: neo4j
          image: api
          name: api
          ports:
            - containerPort: 4001
          resources: {}
      restartPolicy: Always
status: {}
