apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o charts/fluxcapacitor -f fluxcapacitor-app/docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o charts/fluxcapacitor -f fluxcapacitor-app/docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/fluxcapacitor-app-default: "true"
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_apoc_export_file_enabled
              value: "true"
            - name: NEO4J_apoc_import_file_enabled
              value: "true"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: apoc.*
            - name: NEO4J_dbms_shell_enabled
              value: "true"
          image: neo4j
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources: {}
      restartPolicy: Always
status: {}
